# Generated by Django 6.0.5 on 2026-05-27 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название категории")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=20, unique=True, verbose_name="Номер телефона")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("registration_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("position", models.CharField(blank=True, max_length=100, null=True, verbose_name="Должность")),
                ("bio", models.TextField(blank=True, null=True, verbose_name="О мастере")),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название услуги")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена (руб.)")),
                ("duration_minutes", models.PositiveIntegerField(verbose_name="Длительность (мин.)")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="services", to="app.category", verbose_name="Категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="EmployeeService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.employee", verbose_name="Сотрудник")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.service", verbose_name="Услуга")),
            ],
            options={
                "verbose_name": "Услуга сотрудника",
                "verbose_name_plural": "Услуги сотрудников",
                "unique_together": {("employee", "service")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="services",
            field=models.ManyToManyField(
                related_name="employees", through="app.EmployeeService", to="app.service", verbose_name="Оказываемые услуги"
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("appointment_datetime", models.DateTimeField(verbose_name="Дата и время записи")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждена"),
                            ("completed", "Выполнена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="app.client", verbose_name="Клиент"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="app.employee", verbose_name="Мастер"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="app.service", verbose_name="Услуга"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-appointment_datetime"],
            },
        ),
    ]
