# Generated by Django 6.0.5 on 2026-05-27 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-appointment_datetime", "status"], "verbose_name": "Запись на прием", "verbose_name_plural": "Записи на прием"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория услуг", "verbose_name_plural": "Категории услуг"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Мастер", "verbose_name_plural": "Мастера"},
        ),
        migrations.AlterModelOptions(
            name="employeeservice",
            options={"verbose_name": "Услуга мастера", "verbose_name_plural": "Услуги мастеров"},
        ),
        migrations.AlterUniqueTogether(
            name="employeeservice",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="employee",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="services",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Последнее изменение"),
        ),
        migrations.AddField(
            model_name="client",
            name="favorite_masters",
            field=models.ManyToManyField(blank=True, related_name="favorite_clients", to="app.employee", verbose_name="Любимые мастера"),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Работает ли сейчас"),
        ),
        migrations.AddField(
            model_name="employee",
            name="specialty",
            field=models.CharField(default="Мастер", max_length=100, verbose_name="Специализация"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="title",
            field=models.CharField(default="Услуга", max_length=150, verbose_name="Название услуги"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_datetime",
            field=models.DateTimeField(verbose_name="Дата и время сеанса"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("confirmed", "Подтверждена"), ("completed", "Выполнена"), ("canceled", "Отменена")],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="client",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата регистрации"),
        ),
        migrations.AlterField(
            model_name="employeeservice",
            name="employee",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.employee"),
        ),
        migrations.AlterField(
            model_name="employeeservice",
            name="service",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.service"),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="app.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration_minutes",
            field=models.IntegerField(default=30, verbose_name="Длительность (мин)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена"),
        ),
    ]
