# Generated by Django 6.0.5 on 2026-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_social_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
